### ISSUE TITLE
Beta test invite link no longer working 

### ISSUE THREAD

**Issue by starman2908** [kodi-connect/kodi-connect#3]
Hi Tomas, 

Someone's probably already reported this, but just incase.... The beta test invite link from within the device setup website is no longer working (beta test not found message error). Perhaps link needs updating for most recent skill.

Cheers, 

Ryan

**Comment by fred959** [comment]
Hi,
 I see you've been working here but I've not been able to find any data regarding this issue. I see this isn't working as I receive the same error after generation  of the device's secret. Is there a different manner of adding the skill to Alexa that I've missed?

Thanks in advance.

Fred

**Comment by weissenborn** [comment]
Same issue for me ...

Error: Beta test not found

**Comment by LuckyTNT** [comment]
Hello,
I can confirm, same error here.
I used to have beta invite long ago when it was manual invites from kodi forum and my email was listed on device and skill signup page. But now I tried to set everything to work again and could not get skill was not listed on amazon side.
So I removed my email from https://kodiconnect.kislan.sk/alexa-beta-tests and can't add it back due to mentioned error.

**Comment by tkislan** [comment]
https://kodi-connect.github.io
there is a new way how to get this skill running
